version: '2.9'

services:
  application:
    build:
      context: .
    environment:
      CASSANDRA_HOST: database
      CASSANDRA_USER: cassandra
      CASSANDRA_PASSWORD: cassandra
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8000:80"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: cassandra:4.1.3
    volumes:
      - db_data:/var/lib/cassandra
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
volumes:
  db_data:
    driver: local
